### ISSUE TITLE
Mac TEXT font does not display the same with 2022 version 

### ISSUE THREAD

**Issue by lcalvert7495** [xLightsSequencer/xLights-macOS#3]
Mac TEXT font does not display the same with 2022 version as it did in Nov. and Dec. 2021. What Changed? I'm not having to use OS Fonts... 

Text Effects from my last year sequences used 10x10 Fonts and displayed in Boscoyo Tune To MATRIX (10x36) just fine.  Now I must use the "Use OS Fonts" for it to display properly.  Did something change?

**Comment by lcalvert7495** [comment]
Here is what is working. Second screen shot worked in 2021.

![Screen Shot 2022-03-28 at 2 14 48 PM](https://user-images.githubusercontent.com/102526217/160460950-06fdc1b5-f1b4-4c2f-a821-4cd9294fe52b.png)
![Screen Shot 10x10-12 font  2022-03-28 at 2 15 57 PM](https://user-images.githubusercontent.com/102526217/160461172-ad854f5d-a9c3-4e1e-916d-5cb5090f83b8.png)

**Comment by dkulp** [comment]
I just tried this and it seems to be working with recent releases.
